apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mtls-client-egress
  namespace: mtls-demo
spec:
  podSelector:
    matchLabels:
      app: mtls-client
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 203.0.113.0/24 # ajuste para o IP do gateway do parceiro
      ports:
        - protocol: TCP
          port: 443
